// <auto-generated />
namespace Repository.Sql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FileDimensions1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileDimensions1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703212112377_FileDimensions1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
